repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    # NOTE: Ruby files may contain patches after __END__,
    # where we need to keep their coding styles and whitespace.
    -   id: end-of-file-fixer
        exclude: '.*\.rb$'
    -   id: mixed-line-ending
        exclude: '.*\.rb$'
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '.*\.rb$'

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
    -   id: editorconfig-checker
