name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * * # monthly

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # for pip cache
      - name: Create requirements.txt
        uses: 1arp/create-a-file-action@0.4.5
        with:
          file: requirements.txt
          content: pre-commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  style:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Cache Homebrew Bundler RubyGems
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ runner.os }}-rubygems-

    - name: Install Homebrew Bundler RubyGems
      if: steps.cache.outputs.cache-hit != 'true'
      run: brew install-bundler-gems

    - name: Check style
      run: |
        brew audit --strict --online \
          tueda/loops/kira \
          tueda/loops/lanhep \
          tueda/loops/mma-feynrules \
          tueda/loops/qgraf
        brew style Library
